/*
 * File: app/view/MyGridPanel.js
 * Date: Tue Sep 06 2011 00:01:53 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'MyApp.view.ui.MyGridPanel',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});