/*
 * File: app/view/ui/namesWindow.js
 * Date: Wed Sep 07 2011 15:18:03 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NamesApp.view.ui.namesWindow', {
    extend: 'Ext.window.Window',

    height: 541,
    id: 'namesWindow',
    width: 797,
    layout: {
        type: 'fit'
    },
    title: 'All Names',

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'gridpanel',
                id: 'namesGrid',
                title: 'Names Grid',
                store: 'NamesStore',
                viewConfig: {

                },
                columns: [
                    {
                        xtype: 'gridcolumn',
                        width: 272,
                        dataIndex: 'name',
                        editor: {
                            xtype: 'textfield',
                            allowBlank: false
                        },
                        text: 'Name'
                    },
                    {
                        xtype: 'gridcolumn',
                        width: 393,
                        dataIndex: 'address',
                        editor: {
                            xtype: 'textfield',
                            allowBlank: false
                        },
                        text: 'Address'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'country',
                        editor: {
                            xtype: 'textfield',
                            allowBlank: false
                        },
                        text: 'Country'
                    }
                ],
                plugins: [
                    Ext.create('Ext.grid.plugin.RowEditing', {
                        clicksToEdit: 1
                    })
                ]
            }
        ];
        me.tools = [
            {
                xtype: 'tool',
                tooltip: 'Add row',
                type: 'plus'
            },
            {
                xtype: 'tool',
                tooltip: 'Save',
                type: 'save'
            },
            {
                xtype: 'tool',
                tooltip: 'Refresh',
                type: 'refresh'
            }
        ];
        me.callParent(arguments);
    }
});