/*
 * File: app/store/MyDirectStore.js
 * Date: Tue Sep 06 2011 00:03:23 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyDirectStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'MyDirectStore',
            proxy: {
                type: 'direct',
                api: {
                    read: Countries.get
                },
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'code',
                    type: 'string'
                },
                {
                    name: 'value',
                    type: 'string'
                }
            ]
        }, cfg)]);
    }
});