/*
 * File: app/store/NamesStore.js
 * Date: Wed Sep 07 2011 15:18:03 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NamesApp.store.NamesStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'NamesStore',
            proxy: {
                type: 'direct',
                api: {
                    read: Names.load,
                    update: Names.update,
                    create: Names.create
                },
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    messageProperty: 'message',
                    root: 'data'
                }
            },
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'name',
                    type: 'string'
                },
                {
                    name: 'address',
                    type: 'string'
                },
                {
                    name: 'country',
                    type: 'string'
                }
            ]
        }, cfg)]);
    }
});