/*
 * File: app/view/ui/MyViewport.js
 * Date: Mon Sep 05 2011 23:24:57 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MyViewport', {
    extend: 'Ext.container.Viewport',

    id: 'MyViewPort',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'gridpanel',
                autoRender: true,
                id: 'addressBook',
                title: 'Address book',
                store: 'NamesDirectStore',
                columnLines: true,
                viewConfig: {

                },
                plugins: [
                    Ext.create('Ext.grid.plugin.RowEditing', {

                    })
                ],
                dockedItems: [
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'addAddress',
                                id: 'addAddress',
                                text: 'Add Address'
                            }
                        ]
                    }
                ],
                columns: [
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'name',
                        text: 'Name'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'address',
                        text: 'Address'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'country',
                        text: 'Country',
                        field: {
                            xtype: 'combobox',
                            id: 'CountryComboBox',
                            fieldLabel: 'Country',
                            hideLabel: true,
                            displayField: 'value',
                            queryMode: 'local',
                            store: 'CountryDirectStore',
                            valueField: 'code'
                        }
                    }
                ]
            }
        ];
        me.callParent(arguments);
    }
});