/*
 * File: app/view/ui/MyGridPanel.js
 * Date: Tue Sep 06 2011 00:03:23 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MyGridPanel', {
    extend: 'Ext.grid.Panel',

    height: 250,
    width: 400,
    title: 'My Grid Panel',
    store: 'MyDirectStore1',

    initComponent: function() {
        var me = this;
        me.viewConfig = {

        };
        me.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'name',
                text: 'Name'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'address',
                text: 'Address'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'country',
                text: 'Country',
                field: {
                    xtype: 'combobox',
                    fieldLabel: 'Label',
                    displayField: 'value',
                    store: 'MyDirectStore',
                    valueField: 'code'
                }
            }
        ];
        me.callParent(arguments);
    }
});