/*
 * File: app/store/CountryDirectStore.js
 * Date: Mon Sep 05 2011 23:24:57 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.CountryDirectStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CountryDirectStore',
            proxy: {
                type: 'direct',
                api: {
                    read: Countries.get
                },
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'field'
                },
                {
                    name: 'field'
                }
            ]
        }, cfg)]);
    }
});